module.exports = {
  ALMAZRAH_LOCATIONS: [
    'Al Bagra Fortress',
    'Al Malik Airport',
    'Al Mazrah City',
    'Al Safwa Quarry',
    'Al Sharim Pass',
    'Ahkdar Village',
    'East Suburbs',
    'Eastern Outskirts',
    'El Samman Cemetery',
    'Hafid Port',
    'Mawizeh Marshlands',
    'North Industrial',
    'Northwest Mountain',
    'Oasis',
    'Rohan Oil Refinery',
    'Sa’id City',
    'Sarrif Bay',
    'Sattiq Cave Complex',
    'Sawah Village',
    'Southern Outskirts',
    'Taraq Village',
    'Western Foothills',
    'Western Outskirts',
    'Zarqwa Hydroelectric',
    'Zaya Observatory',
  ],
  CALDERA_LOCATIONS: [
    'Airfield',
    'Arsenal',
    'Beachhead',
    'Capital',
    'Docks',
    'Easter Egg: Just insta drop',
    'Fields',
    'Lagoon',
    'Mines',
    'Peak',
    'Power plant',
    'Resort',
    'Runway',
    'Sub pen',
    'Village',
  ],
  REBIRTH_ISLAND_LOCATIONS: [
    'Bioweapon labs',
    'Chemical Eng',
    'Control Center',
    'Decon Zone',
    'Dock',
    'Easter Egg: Just insta drop',
    'Harbor',
    'Headquarters',
    'Living Quarters',
    'Nova 6 Factory',
    'Prison Block',
    'Stronghold',
  ],
  FORTUNES_KEEP_LOCATIONS: [
    'Bay',
    'Camp',
    'Easter Egg: Just insta drop',
    'Gatehouse',
    'Graveyard',
    'Grotto',
    'Keep',
    'Lighthouse',
    'Overlook',
    "Smuggler's Cove",
    'Terraces',
    'Town',
    'Winery',
  ],
};
