module.exports = {
  ALMAZRAH_LOCATIONS: [
    'Ahkdar Village',
    'Al Bagra Fortress',
    'Al Malik Airport',
    'Al Mazrah City',
    'Al Safwa Quarry',
    'Al Samman Cemetery',
    'Al Sharim Pass',
    'Hafid Port',
    'Mawizeh Marshlands',
    'Rohan Oil',
    'Sa’id City',
    'Sarrif Bay',
    'Sattiq Cave Complex',
    'Sawah Village',
    'Taraq Village',
    'Zarqwa Hydroelectric',
    'Zaya Observatory',
  ],
  AREA_99: [
    'Bunker',
    'Cooling Towers',
    'Loading Bay',
    'Mannequin Assembly',
    'Manufacturing',
    'Nuketown Shipping',
    'Pods',
    'Reactor',
    'Test Site',
    'Warehouse',
  ],
  ASHIKA_ISLAND_LOCATIONS: [
    'Beach Club',
    'Ōganikku Farms',
    'Port Ashika',
    'Residential',
    'Shipwreck',
    'Town Center',
    'Tsuki Castle'
  ],
  CALDERA_LOCATIONS: [
    'Airfield',
    'Arsenal',
    'Beachhead',
    'Capital',
    'Docks',
    'Easter Egg: Just insta drop',
    'Fields',
    'Lagoon',
    'Mines',
    'Peak',
    'Power plant',
    'Resort',
    'Runway',
    'Sub pen',
    'Village',
  ],
  REBIRTH_ISLAND_LOCATIONS: [
    'Bioweapon labs',
    'Chemical Eng',
    'Control Center',
    'Decon Zone',
    'Dock',
    'Easter Egg: Just insta drop',
    'Factory',
    'Harbor',
    'Headquarters',
    'Industry',
    'Living Quarters',
    'Nova 6 Factory',
    'Prison',
    'Stronghold',
  ],
  FORTUNES_KEEP_LOCATIONS: [
    'Easter Egg: Just insta drop',
    'Gatehouse',
    'Graveyard',
    'Ground Zero',
    'Keep',
    'Konni Outpost',
    'Lighthouse',
    'Overlook',
    'Pier',
    'Terraces',
    'Town',
    'Winery',
  ],
  VONDEL_LOCATIONS: [
    'Castle',
    'Central Station',
    'City Hall',
    'Cruise Terminal',
    'Exhibit',
    'Fire Department',
    'Floating District',
    'Graveyard',
    'Police Station',
    'Mall',
    'Market',
    'Museum',
    'Stadium',
    'University',
    'Zoo',
  ],
  URZIKSTAN_LOCATIONS: [
    'Hadiqa Farms',
    'Levin Resort',
    'Low Town',
    'Old Town',
    'Orlov Military Base',
    'Popov Power',
    'Seaport District',
    'Shahin Manor',
    'Urzikstan Cargo',
    'Zaravan City',
    'Zaravan Suburbs',
  ],
};
