module.exports = {
  CALDERA_LOCATIONS: [
    'Airfield',
    'Arsenal',
    'Beachhead',
    'Capital',
    'Docks',
    'Easter Egg: Just insta drop',
    'Fields',
    'Lagoon',
    'Mines',
    'Peak',
    'Power plant',
    'Resort',
    'Runway',
    'Sub pen',
    'Village',
  ],
  REBIRTH_ISLAND_LOCATIONS: [
    'Bioweapon labs',
    'Chemical Eng',
    'Control Center',
    'Decon Zone',
    'Dock',
    'Easter Egg: Just insta drop',
    'Harbor',
    'Headquarters',
    'Living Quarters',
    'Nova 6 Factory',
    'Prison Block',
    'Stronghold',
  ],
  FORTUNES_KEEP_LOCATIONS: [
    'Bay',
    'Camp',
    'Easter Egg: Just insta drop',
    'Gatehouse',
    'Graveyard',
    'Grotto',
    'Keep',
    'Lighthouse',
    'Overlook',
    "Smuggler's Cove",
    'Terraces',
    'Town',
    'Winery',
  ],
};
