module.exports = {
  VERDANSK_LOCATIONS: [
    'Airport',
    'Array',
    'Boneyard',
    'Downtown',
    'Easter Egg: Just insta drop',
    'Factory',
    'Farmland',
    'Hills',
    'Hospital',
    'Lumber',
    'Military Base',
    'Park',
    'Port',
    'Prison',
    'Promenade East',
    'Promenade West',
    'Salt Mine',
    'Stadium',
    'Storage Town',
    'Summit',
    'Superstore',
    'TV Station',
    'Train Station',
  ],
  REBIRTH_ISLAND_LOCATIONS: [
    'Bioweapon labs',
    'Chemical Eng',
    'Control Zone',
    'Decon Zone',
    'Harbor',
    'Headquarters',
    'Living Quarters',
    'Nova 6 Factory',
    'Prison Block',
    'Security Area',
    'Shore',
  ],
};
